using System.IO;
using System.Text;
using System.Text.Json.Nodes;
using System.Xml.Linq;

namespace LastEpochHelper.Core;

/// <summary>What a look at a loot filter file found.</summary>
public sealed record FilterReport(
    int Version, int Rules, int Disabled,
    IReadOnlyList<string> NewerUniques, int NewerUniqueCount,
    IReadOnlyList<string> NewerAffixes, int NewerAffixCount,
    IReadOnlyList<string> Notes);

/// <summary>
/// Writes and inspects Last Epoch loot filters. The format is the game's own XML (the files in its
/// Filters folder); element names, including the misspelt "comparsion", are the game's.
/// </summary>
public static class LootFilters
{
    private const int FilterVersion = 9;
    private const string Idols = "IDOL_1x1_ETERRA IDOL_1x1_LAGON IDOL_2x1 IDOL_1x2 IDOL_3x1 IDOL_1x3 IDOL_4x1 IDOL_1x4 IDOL_2x2";
    private static readonly XNamespace Xsi = "http://www.w3.org/2001/XMLSchema-instance";

    // ------------------------------------------------------------------ generating

    /// <summary>
    /// A leveling filter for an imported build: shows everything at first, then hides normal, magic
    /// and finally rare items unless they carry affixes the build uses. Uniques, sets and exalted
    /// items are never hidden. Returns null if the build has no gear to derive affixes from.
    /// </summary>
    public static string? Generate(BuildTree build, string name) => Generate(new[] { build }, name);

    /// <summary>What one or more builds want from drops: the ids loot filter rules are written with.</summary>
    private sealed record Wanted(List<int> GearAffixes, List<int> IdolAffixes, List<int> Uniques)
    {
        public static Wanted From(IEnumerable<BuildTree> builds)
        {
            var stages = builds.SelectMany(b => b.Stages).ToList();
            var gear = stages.SelectMany(s => s.Gear).ToList();
            var idols = stages.SelectMany(s => s.Idols).ToList();
            return new Wanted(
                gear.SelectMany(g => g.AffixIds).Distinct().OrderBy(i => i).ToList(),
                idols.SelectMany(g => g.AffixIds).Distinct().OrderBy(i => i).ToList(),
                gear.Concat(idols).Where(g => g.UniqueId is not null).Select(g => g.UniqueId!.Value).Distinct().OrderBy(i => i).ToList());
        }
    }

    /// <summary>The "never hide these" rules, highest priority first, numbered from <paramref name="firstOrder"/>.</summary>
    private static List<XElement> KeepRules(Wanted wanted, int firstOrder = 0)
    {
        var rules = new List<XElement>();
        void Add(string title, params XElement[] conditions) => rules.Add(Rule("SHOW", title, firstOrder + rules.Count, true, conditions));
        if (wanted.Uniques.Count > 0) Add("Uniques the build uses", UniqueCondition(wanted.Uniques));
        if (wanted.GearAffixes.Count > 0) Add("Two or more build affixes", Rarity("NORMAL MAGIC RARE EXALTED"), Affixes(wanted.GearAffixes, onSameItem: 2));
        if (wanted.IdolAffixes.Count > 0) Add("Idols with a build affix", Types(Idols), Affixes(wanted.IdolAffixes));
        return rules;
    }

    /// <summary>One filter for several builds (a main character and an alt, say): anything either wants is shown.</summary>
    public static string? Generate(IReadOnlyCollection<BuildTree> builds, string name)
    {
        var wanted = Wanted.From(builds);
        var gearAffixes = wanted.GearAffixes;
        if (gearAffixes.Count == 0) return null;
        var build = builds.Count == 1 ? builds.First() : new BuildTree { Name = string.Join(" + ", builds.Select(b => b.Name)) };

        // Highest priority first; the game evaluates Order 0 before Order 1 and so on.
        var rules = KeepRules(wanted);
        void Add(string type, string title, bool emphasized, params XElement[] conditions) =>
            rules.Add(Rule(type, title, rules.Count, emphasized, conditions));

        Add("SHOW", "One build affix", false, Rarity("NORMAL MAGIC RARE"), Affixes(gearAffixes));
        Add("SHOW", "Idols while leveling", false, Types(Idols), CharacterLevel(0, 49));
        Add("SHOW", "Rares while leveling", false, Rarity("RARE"), CharacterLevel(0, 29));
        Add("SHOW", "Everything in the first levels", false, CharacterLevel(0, 9));
        Add("HIDE", "Normal, magic and rare items", false, Rarity("NORMAL MAGIC RARE"));

        // The file lists the lowest priority first, as the game writes it.
        rules.Reverse();
        var document = new XElement("ItemFilter",
            new XAttribute(XNamespace.Xmlns + "i", Xsi),
            new XElement("name", name),
            new XElement("filterIcon", 0),
            new XElement("filterIconColor", 0),
            new XElement("description", $"Generated by Last Epoch Helper from the build \"{build.Name}\". Tightens as you level: all items to level 9, rares to 29, then only items with the build's affixes."),
            new XElement("lastModifiedInVersion", "1.0.0.4"),
            new XElement("lootFilterVersion", FilterVersion),
            new XElement("rules", rules));
        return document.ToString();
    }

    private static XElement Rule(string type, string title, int order, bool emphasized, XElement[] conditions) =>
        new("Rule",
            new XElement("type", type),
            new XElement("conditions", conditions),
            new XElement("recolor", "false"),
            new XElement("color", 0),
            new XElement("isEnabled", "true"),
            new XElement("levelDependent_deprecated", "false"),
            new XElement("minLvl_deprecated", 0),
            new XElement("maxLvl_deprecated", 0),
            new XElement("emphasized", emphasized ? "true" : "false"),
            new XElement("nameOverride", title),
            new XElement("SoundId", 0),
            new XElement("MapIconId", 0),
            new XElement("BeamOverride", "false"),
            new XElement("BeamSizeOverride", "NONE"),
            new XElement("BeamColorOverride", 0),
            new XElement("Order", order));

    private static XElement Condition(string type, params object[] content) =>
        new("Condition", new XAttribute(Xsi + "type", type), content);

    private static XElement Rarity(string rarities) => Condition("RarityCondition", new XElement("rarity", rarities));

    private static XElement CharacterLevel(int min, int max) =>
        Condition("CharacterLevelCondition", new XElement("minimumLvl", min), new XElement("maximumLvl", max));

    private static XElement Types(string types) =>
        Condition("SubTypeCondition",
            new XElement("type", types.Split(' ').Select(t => new XElement("EquipmentType", t))),
            new XElement("subTypes"));

    private static XElement Affixes(IEnumerable<int> ids, int onSameItem = 1) =>
        Condition("AffixCondition",
            new XElement("affixes", ids.Select(i => new XElement("int", i))),
            new XElement("comparsion", "ANY"),
            new XElement("comparsionValue", 1),
            new XElement("minOnTheSameItem", onSameItem),
            new XElement("combinedComparsion", "ANY"),
            new XElement("combinedComparsionValue", 1),
            new XElement("advanced", onSameItem > 1 ? "true" : "false"));

    private static XElement UniqueCondition(IEnumerable<int> ids) =>
        Condition("UniqueModifiersCondition",
            ids.Select(i => new XElement("Uniques", new XElement("UniqueId", i), new XElement("Rolls"))));

    /// <summary>
    /// A copy of an existing filter with the builds' "never hide" rules placed above everything in
    /// it: their uniques, items with two or more of their affixes, idols with their affixes. The
    /// filter's own rules keep their order, just below.
    /// </summary>
    /// <returns>Null if the builds have nothing to add or the file is not a filter.</returns>
    public static string? AddKeepRules(string filterXml, IReadOnlyCollection<BuildTree> builds, string newName)
    {
        var document = XDocument.Parse(filterXml);
        var rules = document.Root?.Element("rules");
        if (document.Root is null || rules is null) return null;
        var keep = KeepRules(Wanted.From(builds));
        if (keep.Count == 0) return null;

        // Everything already there moves down by as many places as are inserted at the top.
        foreach (var order in rules.Elements("Rule").Select(r => r.Element("Order")).Where(o => o is not null))
            order!.Value = ((int)order + keep.Count).ToString();
        // The file lists the lowest priority first, so the new top rules go last, Order 0 at the very end.
        keep.Reverse();
        rules.Add(keep);
        if (document.Root.Element("name") is { } name) name.Value = newName;
        return document.ToString();
    }

    // ------------------------------------------------------------------ inspecting

    /// <summary>
    /// Looks for signs that a filter is older than the game: ids are handed out in order, so uniques
    /// and affixes with a higher id than anything the filter mentions were added after it was made.
    /// </summary>
    /// <param name="game">Maxroll's game data (for names); null gives the structural checks only.</param>
    public static FilterReport Inspect(string xml, JsonNode? game)
    {
        var document = XDocument.Parse(xml);
        var root = document.Root ?? throw new System.Xml.XmlException("Empty filter.");
        int version = (int?)root.Element("lootFilterVersion") ?? 0;
        var rules = root.Element("rules")?.Elements("Rule").ToList() ?? new List<XElement>();
        int disabled = rules.Count(r => string.Equals((string?)r.Element("isEnabled"), "false", StringComparison.OrdinalIgnoreCase));

        var affixIds = rules.Descendants("affixes").Elements("int").Select(e => (int)e).ToHashSet();
        var uniqueIds = rules.Descendants("UniqueId").Select(e => (int)e).ToHashSet();

        var notes = new List<string>();
        if (version < FilterVersion) notes.Add($"Written for filter format {version}; the game is on {FilterVersion} and converts it when loaded.");
        if (rules.Count > 75) notes.Add($"{rules.Count} rules - the support site gives 75 as the limit, though larger filters are in use.");
        if (disabled > 0) notes.Add($"{disabled} rule(s) are switched off.");

        var newerUniques = new List<string>();
        var newerAffixes = new List<string>();
        // Only meaningful for filters that list uniques / affixes broadly; a filter naming three uniques is not "missing" the rest.
        if (game is not null && uniqueIds.Count >= 20)
        {
            int newest = uniqueIds.Max();
            newerUniques = (game["uniques"] as JsonArray ?? new JsonArray())
                .Where(u => (u?["uniqueID"].IntOrNull() ?? -1) > newest)
                .Select(u => Name(u, "displayName", "name")).Where(n => n.Length > 0).ToList();
        }
        if (game is not null && affixIds.Count >= 40)
        {
            int newest = affixIds.Max();
            newerAffixes = (game["affixes"] as JsonArray ?? new JsonArray())
                .Where(a => (a?["affixId"].IntOrNull() ?? -1) > newest)
                .Select(a => Name(a, "affixDisplayName", "affixName")).Where(n => n.Length > 0).Distinct().ToList();
        }
        if (game is null) notes.Add("Import a Maxroll build once to enable the check for uniques and affixes newer than the filter.");

        return new FilterReport(version, rules.Count, disabled,
            newerUniques.Take(12).ToList(), newerUniques.Count, newerAffixes.Take(12).ToList(), newerAffixes.Count, notes);
    }

    private static string Name(JsonNode? node, params string[] keys)
    {
        foreach (string key in keys)
            if (node?[key].StrOrNull() is { Length: > 0 } text) return text;
        return "";
    }

    /// <summary>A file-system safe filter name for a build.</summary>
    public static string FileNameFor(string buildName)
    {
        var name = new StringBuilder("LEH ");
        foreach (char c in buildName) name.Append(Path.GetInvalidFileNameChars().Contains(c) ? '_' : c);
        return name.ToString().Trim();
    }
}
